### ISSUE TITLE
why python 2? 

### ISSUE THREAD

**Issue by infomaven** [ticarpi/jwt_tool#1]
I'm new to Python, and also newer to security.

This seems like a newer project. 
Why did you write it in Python 2 when end of life for python 2 now has a definite date? 

No judgement here...I'm just trying to learn.

**Comment by ticarpi** [comment]
Honestly, because I learnt Python 2.x first - it is ubiquitous, pre-installed on almost all Linux machines I happen to run commands on, and still has wide support from a huge back-catalogue of libraries. That, and most projects I use are still not Python 3...
I'll migrate this to Python 3 before EOL, but not a high priority for now.

**Comment by infomaven** [comment]
Fair enough.


I think I might have mentioned that I'm fairly new to Python, and the struggle between python2 and python3 seems epic and kind of mind-boggling.


 In fact, for a long time I avoided learning Python because of this.


However now I need to learn it for my day job, so I'm wading into the fray.


If you need any help with porting this over, I'd be glad to help.


________________________________

**Comment by ticarpi** [comment]
Well I took my sweet time, but it's finally done - commit 0e0b33566972f6b2186ad9c682239de1fd50a672
Python3 for the masses.
