### ISSUE TITLE
termcolor output control characters instead of colored text in the Windows console?

### ISSUE THREAD

**Issue by randyarios** [ticarpi/jwt_tool#29]
when try to run in windows 10, the out put is not colored, or this only work for linux only ?

**Comment by ticarpi** [comment]
Good question. I run this in Windows, but under WSLv1 (Windows Subsystem for Linux) - tested in Ubuntu and Kali.  

Yes, you do get the control chars in Windows cmd/Powershell - a quick fix is to import coloroma and init that by adding these lines to the beginning of the import block in jwt_tool.py:
`import colorama`  
`colorama.init()`  

This can be installed from pip using:
`python3 -m pip install colorama`

Currently I haven't done this to minimise imports, and because running jwt_tool under Windows can be very laggy - particularly in the scanning modes - and I haven't worked out why yet.  
If people want Windows supported I'll add that import, but I feel most users are running it under Linux [citation needed].

**Comment by randyarios** [comment]
problem solved
![color_solved_forwindows](https://user-images.githubusercontent.com/3500015/98740394-8faa9d80-23dd-11eb-8a76-ed4ef3a3575c.jpg)

**Comment by randyarios** [comment]
i think you need to add this info in readme.md.. maybe it can help for other windows user

**Comment by ticarpi** [comment]
Agreed.  
I'm reviewing an update now anyway, so I'll add in a commented fix and note how to resolve it in README  
Thanks for the input
